# Run `pre-commit autoupdate` to update the hook versions.

repos:
  - repo: 'meta'
    hooks:
      - id: 'check-hooks-apply'
      - id: 'check-useless-excludes'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - 'flake8-bugbear==24.1.17'

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: 'https://github.com/python-jsonschema/check-jsonschema'
    rev: '0.27.4'
    hooks:
      - id: 'check-dependabot'
      - id: 'check-github-workflows'
