name: Python linting
on: [push, pull_request]
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # v4.1.1
      - uses: 'actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c' # v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run linting
        run: pre-commit run -a
